#!/usr/bin/env bash
# tell_the_story_of_passwd
while IFS=':' read -r username password uid gid info home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
