#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and: displays bad luck for the 4th loop iteration, displays good luck for the 8th loop iteration, displays Best School for the other iterations
x=1
while [ $x -le 10 ]
do
echo "Best School"
if [ $x -eq 4 ]
then
echo "bad luck"
elif [ $x -eq 8 ]
then
echo "good luck"
else
then
echo "Best School"
fi
x=$(( x + 1))
done
