#!/usr/bin/env bash
# Prints from 1 to 20 with case conditions
x=1
y=20
while [ $x -ge $y ]
do
if [ $x -eq 4 ]
then
echo "bad luck from China"
elif [ $x -eq 9 ]
then
echo "bad luck from Japan"
elif [ $x -eq 17 ]
then
echo "bad luck from Italy"
else
echo $x
fi
x=$(( x + 1))
done
