#!/usr/bin/env bash
# Prints from 1 to 20 with case conditions
x=1
y=20
while [ $x -ge $y ]
do
echo $x
case $x in
4)
echo “bad luck from China”
;;
9)
echo “bad luck from Japan”
;;
17)
echo “bad luck from Italy”
;;
esac
let x=$x+1
done
