#!/usr/bin/env bash
# create pub file with its own pid and receive SIG
function love() {
rm /var/run/holbertonscript.pid
exit
}

trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT

echo $$ >> /var/run/holbertonscript.pid
while 'true'; do
echo To infinity and beyond;
done
