#!/usr/bin/env bash
# Scritp that display To infinity and beyond indefinitely with sleep 2
# I am invincible!!! when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
echo "To infinity and beyond"
sleep 10
done
